version: ${project.version}
stats: true
settings:
  event-priority: LOWEST
  auto-save: true
  save-interval: 10
  color-override: false
  notify-others: true
  join-message: true
  confirm-timeout: 15
  default-color: '&f'
  command-name: 'chatcolor'
  force-group-colors: true
  default-color-enabled: true
  command-opens-gui: false
default:
  code: '1'
  color: '&f'