name: ChatColor2
main: com.sulphate.chatcolor2.main.ChatColor
version: 1.12
api-version: "1.13"
author: Sulphate

softdepend: [ PlaceholderAPI ]

commands:

  chatcolor:
    description: main command for ChatColor 2.
    usage: /<command> [player] <color> [modifiers]