name: ChatColor2
main: com.sulphate.chatcolor2.main.MainClass
version: 1.6.9
author: Sulphate

commands:

  chatcolor:
    description: main command for ChatColor 2.
    usage: /<command> [player] <color> [modifiers]

  confirm:
    description: Confirms a choice within ChatColor 2.
    usage: /<command>