name: ChatColor2
main: com.sulphate.chatcolor2.main.ChatColor
version: 1.8.0
author: Sulphate

softdepend: [ PlaceholderAPI ]

commands:

  chatcolor:
    description: main command for ChatColor 2.
    usage: /<command> [player] <color> [modifiers]

  confirm:
    description: Confirms a choice within ChatColor 2.
    usage: /<command>