name: ChatColor2
main: com.sulphate.chatcolor2.main.ChatColor
version: 1.10.4
api-version: "1.16"
author: Sulphate

softdepend: [ PlaceholderAPI ]

commands:

  chatcolor:
    description: main command for ChatColor 2.
    usage: /<command> [player/confirm] <color/default> [modifiers]